services:
  watsup:
    build: .
    ports:
      - "3000:3000"
    environment:
      WATSUP_CONFIG_PATH: /run/configs/watsup.toml
    configs:
      - source: watsup-dashboard
        target: /run/configs/watsup.toml

configs:
  watsup-dashboard:
    file: ./config/default.toml
